### ISSUE TITLE
Side menu rendering not smooth in updated UI

### ISSUE THREAD

**Issue by glennjacobs** [getcandy/getcandy#442]
@markmead this is for you.

When I click around the new admin hub UI (with the menu expanded), the side menu isn't very smooth. It seems it initially renders collapsed and then a few ms later it pops open. Can you work your magic?

**Comment by markmead** [comment]
It's because we're using `defer` on the Alpine JS script which is the recommended approach.

As this video highlights, the best result is when removing `defer` but that's not really an option in my opinion. There's some improvement when Alpine JS is bundled but it's not perfect.

https://user-images.githubusercontent.com/50486078/182105870-9acefb34-28e4-48e4-8066-85c2ab5e5c2b.mov

**Comment by glennjacobs** [comment]
@markmead I'm not an expert on this subject, so can't really comment. But currently, I would say it's not acceptable, so we'll need to find a way to resolve it.

@alecritson do you have any ideas?

**Comment by alecritson** [comment]
@glennjacobs Not too sure what the perfect solution is really. As it stands we gotta wait for Alpine's storage to kick in and add the correct classes. Only thing I can think of atm is storing the preference in a cookie and grabbing it server side so we can set the correct class on render, before Alpine takes over.

**Comment by glennjacobs** [comment]
@alecritson yeah, I think that's correct. It really needs to be server-side.

**Comment by alecritson** [comment]
@glennjacobs Currently we don't have anything in the hub to set this kind of info and retrieve it, I guess we can use the `GetCandyHub` ? 🤔 

Then we'd probably need a bit of a rewrite of the menu so we can tap into Livewire (since they're just layout files atm) so not sure this would be a "quick fix" if you're wanting it for the next release.

**Comment by alecritson** [comment]
This should be sorted in the latest release.
